CP-542 draft
COMATCH/comatch-design-system pull request #36
Opened 2021-02-01 11:03 UTC by Ebazhanov

draft

2021-02-01 11:37 UTC, stanimir-stoychev requested changes

2021-02-01 11:37 UTC, stanimir-stoychev commented on src/components/DownloadButton/DownloadButton.tsx
> +            {children}
If I remember the design correctly, there's an Icon associated with the download button. Can you add it here?

2021-02-06 18:24 UTC, Ebazhanov commented on src/components/DownloadButton/DownloadButton.tsx
> +            {children}
thanks, update @stanimir-stoychev

2021-02-08 09:54 UTC, stanimir-stoychev commented on src/components/DownloadButton/DownloadButton.tsx
> +                <FontAwesomeIcon className="icon" icon={faCheck} />
Good, now I think you might need to add some styling to this. What do you think?

2021-09-15 16:02 UTC, closed without merging