CP-1436 Snackbar component
COMATCH/comatch-design-system pull request #46
Opened 2021-04-30 12:29 UTC by s-latif

2021-05-05 05:44 UTC, jlambdev approved these changes
It looks all good to me, maybe worth a check from Stan as well in case I miss anything. We have a POC to work on in our current sprint and can use this component as well when it's ready :)

2021-05-05 05:44 UTC, jlambdev commented on src/containers/stories/Snackbar.stories.tsx
> +                </Button>{' '}
Can you adjust the positioning instead of using `{' '}` here? Not critical as it's just a .stories.tsx file

2021-05-05 07:29 UTC, stanimir-stoychev requested changes
Looking good!

2021-05-05 07:29 UTC, stanimir-stoychev commented on src/containers/Snackbar/Snackbar.tsx
> +const SlideTransition = (props: TransitionProps) => {
If you're not going to export the component then there's no need to wrap it like the rest ;)

2021-05-05 07:29 UTC, stanimir-stoychev commented on src/containers/Snackbar/Snackbar.tsx
> +    autoHideDuration = 20000,
20 seconds by default? Maybe we can lower that to 3-5?

2021-05-05 07:29 UTC, stanimir-stoychev commented on src/containers/Snackbar/Snackbar.tsx
> +    const handleClose = (event: React.SyntheticEvent<HTMLElement>, reason: SnackbarCloseReason) => {
If you make this into a `curried` function you can have a much simpler statement on line 58 where you're using the actual function - e.g. onClick = { handleClose('clickaway') }

2021-05-05 07:29 UTC, stanimir-stoychev commented on src/containers/Snackbar/styled.ts
> +    ${({ severity, theme }) => {
Last time I tried this I noticed that having multiple functions rather than one is more performant for the components - each prop that requires a function gets one rather than one function for al props

2021-05-05 07:29 UTC, stanimir-stoychev commented on src/containers/Snackbar/styled.ts
> +        const { spacing } = theme;
Also you destructured the spacing function but didn't do that for the palettes. Please do both for consistency

2021-05-05 07:29 UTC, stanimir-stoychev commented on src/containers/Snackbar/styled.ts
> +    ${({ theme }) => {
Same here for the function part

2021-05-05 07:29 UTC, stanimir-stoychev commented on src/containers/Snackbar/styled.ts
> +    ${({ theme }) => {
Here as well

2021-05-05 07:29 UTC, stanimir-stoychev commented on src/containers/Snackbar/styled.ts
> +                display: flex;
Also if you like to mess around I also try to alphabetize the props

2021-05-05 07:29 UTC, stanimir-stoychev commented on src/containers/Snackbar/types.ts
> +export type ComponentContext = {
I recently learned that using `interfaces` gives you better messages in the code editor. Can I ask you to switch to interfaces?

2021-05-05 07:29 UTC, stanimir-stoychev commented on src/containers/stories/Snackbar.stories.tsx
> +                </Button>{' '}
You can simply wrap the `PageWrapper` into our own styled component and in there target Buttons that are next to each other and then give them the extra spacing in a cleaner way ;)

2021-05-05 07:29 UTC, stanimir-stoychev commented on src/containers/Snackbar/Snackbar.tsx
> +export const SnackbarContext = React.createContext<ComponentContext>({
Rather than exporting the `context` directly how do you feel about an abstraction? I'd suggest to move the Notifications/Snackbar component to `containers` since it seems to behave like a container and then in there you can create the HOC, the ContextProvider, and any other logic that you need. I'd also suggest to create the accessors to your context there and expose those. This will allow developers to use the desired functionality without having to have to know that there's an extra context that needs to be accessed and thus having to have to stitch that logic every time it's needed. You can simply expose a bunch of `custom hooks` that when called with do the context stitching for you 😉

2021-05-05 13:02 UTC, s-latif commented on src/containers/Snackbar/Snackbar.tsx
> +const SlideTransition = (props: TransitionProps) => {
On line 73 following were two possibilities
```
 1. TransitionComponent={SlideTransition} 
 2. TransitionComponent={(props: TransitionProps) => <Slide {...props} direction="up" />}
 ```
 
Not much difference but i liked option 1 from code readability point of view.

2021-05-05 13:02 UTC, s-latif commented on src/containers/Snackbar/Snackbar.tsx
> +    autoHideDuration = 20000,
This is what recommended by design https://app.zeplin.io/project/5a291fa3dd015b9e085b67e2/screen/607da574ed219496bb6b0411

2021-05-05 13:03 UTC, s-latif commented on src/containers/Snackbar/Snackbar.tsx
> +    const handleClose = (event: React.SyntheticEvent<HTMLElement>, reason: SnackbarCloseReason) => {
unfortunately we cant really make it a curry function cz `handleClose` is also used internally by `Snackbar` for autoHide after elapsing `autoHideDuration`

2021-05-05 13:03 UTC, s-latif commented on src/containers/Snackbar/styled.ts
> +    ${({ severity, theme }) => {
if you think having one function for all props gonna have a significant impact on performance than i will be happy to update.

From code reusability and maybe readability point of view i like the option 2 from the following
```
1. 
color: ${({theme: { palettes }}) => ${palettes[severity].dark.bgColor};}
background-color: ${({theme: { palettes }}) => ${palettes[severity].light.bgColor};}

2. 
${({theme: { palettes }}) => {

color: ${palettes[severity].dark.bgColor};
background-color: ${palettes[severity].light.bgColor};

}}

```

2021-05-05 13:03 UTC, s-latif commented on src/containers/Snackbar/styled.ts
> +                display: flex;
if you mean alphabetising `MuiSnackbarContent-root` its from material UI and here just gonna override its existing style. happy to hear further ideas to make it better

2021-05-10 10:03 UTC, stanimir-stoychev approved these changes
LGTM

2021-05-10 10:27 UTC, stanimir-stoychev submitted a review, later dismissed
LGTM

2021-05-18 15:17 UTC, harman052 approved these changes

2021-05-19 06:36 UTC, stanimir-stoychev requested changes
Good job, just few tiny things to take care of

2021-05-19 06:36 UTC, stanimir-stoychev commented on README.md
> +8. `yarn build` (generate the new bundle)
This is already step 2 from deployment

2021-05-19 06:36 UTC, stanimir-stoychev commented on README.md
> +11. Deploy **storybook** to **Github Pages**:
```suggestion
3. `npm publish` (will publish to the *npm registry*)
4. `git push origin master` (push version commit to master)
5. Create tag with latest version of the package:
    - `git tag <VERSION_NUMBER_IN_PACKAGE_JSON>`
    - `git push origin <VERSION_NUMBER_IN_PACKAGE_JSON>`
6. Deploy **storybook** to **Github Pages**:
```

2021-05-19 11:52 UTC, s-latif commented on README.md
> +8. `yarn build` (generate the new bundle)
at step2 we update the version with `npm version major|minor|patch` after `yarn build`. The reason of updating version after creating build in step-2 was to identify any kind of error which were not identified earlier.

2021-05-19 12:58 UTC, stanimir-stoychev approved these changes
LGTM

2021-05-19 13:46 UTC, merged