add toggle switch checkbox component
COMATCH/comatch-design-system pull request #53
Opened 2021-05-10 11:37 UTC by Ebazhanov

![image](https://user-images.githubusercontent.com/13170022/117653484-c0a13a80-b194-11eb-8989-0b9709b5e5cb.png)

2021-05-10 11:46 UTC, stanimir-stoychev approved these changes
LGTM

2021-05-10 11:46 UTC, stanimir-stoychev commented on src/components/Switch/styled.ts
> +const StyledSwitch = withStyles({
Please use `styled-components`

2021-05-10 11:46 UTC, stanimir-stoychev commented on src/components/Switch/styled.ts
> +import palettes from '../../style/theme/palettes';
Don't import styles, please. When you just import it like this it won't ever change and thus it will break the logic of the Provider

2021-05-10 11:46 UTC, stanimir-stoychev commented on src/components/Switch/styled.ts
> +import { withStyles } from '@material-ui/core';
```suggestion
import styled from 'styled-components';
```

2021-05-10 11:46 UTC, stanimir-stoychev commented on src/components/Switch/types.ts
> +export type SwitchProps = Partial<FormControlLabelProps> &
Convert this to an `interface` please

2021-05-10 11:48 UTC, stanimir-stoychev requested changes
Can you please attend to the comments

2021-05-10 11:56 UTC, s-latif commented on src/components/Switch/styled.ts
> +import palettes from '../../style/theme/palettes';
@Ebazhanov please let me or Stan know if you need help to understand the concept of provider. If you already familiar with it that is awesome.

2021-05-12 07:00 UTC, stanimir-stoychev reviewed
Good job!

2021-05-12 07:00 UTC, stanimir-stoychev commented on src/components/Switch/types.ts
> +    label: ReactNode | LabelWithProps;
This is a great prop but you're not using it properly. If you check the other components you'll notice that there's a helper function that can render the label. I suggest you use that in your component 😉

2021-05-12 07:00 UTC, stanimir-stoychev commented on src/components/Switch/types.ts
> +    label: ReactNode | LabelWithProps;
Once you add that please also add the examples where you're using the prop to the stories - e.g. a story with passing a string, ReactNode, and the Array with a node and props for the label

2021-05-17 06:44 UTC, stanimir-stoychev approved these changes
LGTM

2021-05-17 07:11 UTC, merged