draft
COMATCH/comatch-design-system pull request #59
Opened 2021-05-18 15:45 UTC by Ebazhanov

draft

2021-05-25 13:10 UTC, dulik06 commented on src/components/Autocomplete/types.ts
> +export type OptionType = { title: string };
somehow my comment was delated or I dont see it anymore. I would suggest to have options as an array of objects with title and a value

2021-05-25 13:12 UTC, dulik06 commented on src/components/Autocomplete/types.ts
> +export type OptionType = { title: string };
export type OptionType = { title: string, value: string };

2021-05-25 13:13 UTC, dulik06 commented on src/components/Autocomplete/Autocomplete.tsx
> +                                    <IconButton onClick={() => onDelete(v.title)}>
if we have OptionType = { title: string, value: string }; then we should pass value to onDelete

2021-05-25 17:06 UTC, Ebazhanov commented on src/components/Autocomplete/Autocomplete.tsx
> +            />
thanks, updated

2021-05-25 17:07 UTC, Ebazhanov commented on src/components/Autocomplete/types.ts
> +export type OptionType = { title: string };
thanks, updated

2021-05-25 17:07 UTC, Ebazhanov commented on src/components/Autocomplete/Autocomplete.tsx
> +                                    <IconButton onClick={() => onDelete(v.title)}>
thanks, updated

2021-05-25 18:09 UTC, harman052 requested changes

2021-05-25 18:09 UTC, harman052 commented on src/components/stories/Autocomplete.stories.tsx
> +            }}
You don't have to group props. Just provide them in the way Material-UI expects, i.e. directly to `AutocompleteComponent`.

2021-05-25 18:09 UTC, harman052 commented on src/components/Autocomplete/types.ts
> +export interface AutocompletePropsTypes extends WithClassAndId, WithCssGeneratorFunction {
You need to extend `AutocompleteProps`. Import it in line 3 as:
`import { AutocompleteProps } from '@material-ui/lab';`

2021-05-25 18:09 UTC, harman052 commented on src/components/Autocomplete/types.ts
> +    };
I believe all these props already comes typed Material-UI and therefore you don't have to type them again here. They should be safe to remove from here.

2021-05-26 07:14 UTC, stanimir-stoychev requested changes
Almost there

2021-05-26 07:14 UTC, stanimir-stoychev commented on src/components/Autocomplete/Autocomplete.tsx
> +                multiple
👍

2021-05-26 07:14 UTC, stanimir-stoychev commented on src/components/Autocomplete/styled.ts
> +        font-size: 10px;
There's a value in the theme that you can use for this

2021-05-26 07:14 UTC, stanimir-stoychev commented on src/components/Autocomplete/types.ts
> +export interface AutocompletePropsTypes extends WithClassAndId, WithCssGeneratorFunction {
👍

2021-05-26 07:14 UTC, stanimir-stoychev commented on src/components/Autocomplete/types.ts
> +    };
I don't know but what Harman mentioned seems valid

2021-05-26 07:14 UTC, stanimir-stoychev commented on src/components/stories/Autocomplete.stories.tsx
> +            }}
👍

2021-05-27 08:38 UTC, stanimir-stoychev approved these changes
LGTM

2021-05-27 12:28 UTC, harman052 commented on src/components/Autocomplete/Autocomplete.tsx
> +                renderTags={() => null}
We are doing anything with `renderTags` prop so let handled by `...rest`. We can remove it safely.

2021-05-27 12:51 UTC, harman052 requested changes
Just couple of minor comments. Good job!

2021-05-27 12:51 UTC, harman052 commented on src/components/Autocomplete/Autocomplete.tsx
> +export default AutocompleteComponent;
I think name `Autocomplete` is simple and short.

2021-05-27 15:12 UTC, Ebazhanov commented on src/components/Autocomplete/types.ts
> +        Omit<AutocompleteProps<OptionType, any, any, any>, 'className' | 'renderInput'> {
Right now we have story with only `Multiple` and `FreeSolo` props
if it is make sense instead of `any` using e.g. `boolean` or `boolean | undefined` I am fine to replace it. 
Harman please advise what could be the solution?
FYI 
```
export interface AutocompleteProps<
  T,
  Multiple extends boolean | undefined,
  DisableClearable extends boolean | undefined,
  FreeSolo extends boolean | undefined
>
```

2021-05-27 15:12 UTC, Ebazhanov commented on src/components/Autocomplete/Autocomplete.tsx
> +export default AutocompleteComponent;
thanks, updated

2021-05-28 06:51 UTC, stanimir-stoychev commented on src/components/Autocomplete/Autocomplete.tsx
> +                    {value.map((v) => (
BTW, an empty array isn't a problem, the map method will exit without even running the passed function since there aren't any elements to run it on. The problem would be if someone provides something other than an array, like an undefined but that should also be fine as long as the props of the component require this

2021-05-28 06:54 UTC, stanimir-stoychev requested changes

2021-05-28 06:54 UTC, stanimir-stoychev commented on src/components/Autocomplete/Autocomplete.tsx
> +                    (rest.value as OptionType[]).map((v) => (
```suggestion
                    (Array.isArray(rest.value) ? rest.value : []).map((v) => (
```

2021-05-28 08:12 UTC, dulik06 submitted a review, later dismissed

2021-05-28 15:13 UTC, Ebazhanov commented on src/components/Autocomplete/Autocomplete.tsx
> +                    (rest.value as OptionType[]).map((v) => (
thx, updated

2021-05-28 15:13 UTC, Ebazhanov commented on src/components/Autocomplete/types.ts
> +        Omit<AutocompleteProps<OptionType, any, any, any>, 'className' | 'renderInput'> {
updated

2021-05-28 15:49 UTC, harman052 approved these changes

2021-05-28 16:41 UTC, dulik06 approved these changes

2021-05-31 06:52 UTC, stanimir-stoychev approved these changes
LGTM

2021-05-31 06:55 UTC, merged