add limit + styled drop down list
COMATCH/comatch-design-system pull request #66
Opened 2021-05-31 10:09 UTC by Ebazhanov

draft

2021-06-01 07:48 UTC, stanimir-stoychev requested changes

2021-06-01 07:48 UTC, stanimir-stoychev commented on src/components/Autocomplete/styled.ts
> +        background-color: #edf6f8;
Don't hardcode colors

2021-06-01 07:48 UTC, stanimir-stoychev commented on src/components/Autocomplete/Autocomplete.tsx
> +                PaperComponent={({ children }) => <StyledPaper>{children}</StyledPaper>}
There is no way for me to pass anything here as a dev... Add these props to the component's props as well for flexibility

2021-06-01 07:48 UTC, stanimir-stoychev commented on src/components/stories/Autocomplete.stories.tsx
> +import { createFilterOptions } from '@material-ui/lab';
Maybe you can export this function as well then, it seems useful and once we publish the DS it won't be available unless you export it explicitly

2021-06-02 06:27 UTC, stanimir-stoychev requested changes

2021-06-02 06:27 UTC, stanimir-stoychev commented on src/components/Autocomplete/Autocomplete.tsx
> +                PaperComponent={({ children }) => <StyledPaper>{children}</StyledPaper>}
You still didn't add them, though... There's no way for the developer to provide something else for the PaperComponent prop and the renderOption one too...

2021-06-02 06:27 UTC, stanimir-stoychev commented on src/style/theme/hover.ts
> +        bgColor: '#EDF6F8' as '#EDF6F8',
You just extended the theme? Why? Isn't the color there already? If not then maybe we shouldn't use it... You need to collaborate that with Rafa and try not to change the theme whenever you get a value that doesn't make sense

2021-06-02 06:27 UTC, stanimir-stoychev commented on src/style/theme/index.ts
> +    hover,
Hover? What's the idea of this? Are all of our components going to hover with the same color? What's the point of having the palettes if we're just going to do this instead?

2021-06-03 14:00 UTC, dulik06 requested changes

2021-06-03 14:00 UTC, dulik06 commented on src/components/Autocomplete/Autocomplete.tsx
>  }
The options object should hava a label and value. Please change it here:

` <div key={v.title}>` and `{v.title}` to ` <div key={v.value}>` and `{v.label}`

2021-06-07 12:34 UTC, stanimir-stoychev requested changes

2021-06-07 12:34 UTC, stanimir-stoychev commented on src/components/Autocomplete/types.ts
> +export type OptionType = { lable: string; value: string };
Why `table`?

2021-06-07 12:34 UTC, stanimir-stoychev commented on src/components/Autocomplete/styled.ts
> +    padding: 10px;
Use the `theme`

2021-06-07 13:05 UTC, stanimir-stoychev commented on src/components/Autocomplete/styled.ts
> +    padding: ${({ theme: { spacing } }) => spacing(2)}; ;
```suggestion
    padding: ${({ theme: { spacing } }) => spacing(2)};
```

2021-06-07 13:05 UTC, stanimir-stoychev submitted a review, later dismissed
LGTM

2021-06-07 13:25 UTC, stanimir-stoychev approved these changes
LGTM

2021-06-07 13:35 UTC, merged