Hided default arrows of input type number
COMATCH/comatch-design-system pull request #98
Opened 2021-08-25 07:25 UTC by MiguelP1989

2021-08-25 14:19 UTC, harman052 requested changes

2021-08-25 14:19 UTC, harman052 commented on src/components/Currency/styled.ts
> +        input::-webkit-inner-spin-button {
Can we try some other approach? MDN discourages using these properties as these are non standard. https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-outer-spin-button

2021-08-25 14:21 UTC, MiguelP1989 commented on src/components/Currency/styled.ts
> +        input::-webkit-inner-spin-button {
Didn't see this coming!! I will see if there is another alternative! Thanks
We can remove also the type property "number".

2021-08-25 14:27 UTC, harman052 commented on src/components/Currency/styled.ts
> +        input::-webkit-inner-spin-button {
I found this:

```<input type="text" inputmode="numeric" pattern="[0-9]*">```

from https://stackoverflow.com/questions/3790935/can-i-hide-the-html5-number-input-s-spin-box

2021-08-25 14:29 UTC, MiguelP1989 commented on src/components/Currency/styled.ts
> +        input::-webkit-inner-spin-button {
Nice find!! ;)

2021-08-30 14:35 UTC, harman052 reviewed
One tiny comment.

2021-08-30 14:35 UTC, harman052 commented on src/components/Currency/hooks.ts
> +                value: nextValue ? nextValue : '',
Your linter should have complaint here. We can simplify it as:

```suggestion
                value: nextValue || '',
```

2021-08-30 15:06 UTC, MiguelP1989 commented on src/components/Currency/hooks.ts
> +                value: nextValue ? nextValue : '',
done ;)

2021-08-30 15:09 UTC, harman052 approved these changes

2021-08-30 15:10 UTC, merged